// Code generated by "stringer -linecomment -type=NotifyState"; DO NOT EDIT.

package daemon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SdNotifyReady-0]
	_ = x[SdNotifyStopping-1]
	_ = x[SdNotifyReloading-2]
	_ = x[SdNotifyWatchdog-3]
}

const _NotifyState_name = "\"READY=1\"\"STOPPING=1\"\"RELOADING=1\"\"WATCHDOG=1\""

var _NotifyState_index = [...]uint8{0, 9, 21, 34, 46}

func (i NotifyState) String() string {
	if i < 0 || i >= NotifyState(len(_NotifyState_index)-1) {
		return "NotifyState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotifyState_name[_NotifyState_index[i]:_NotifyState_index[i+1]]
}
